package home

import (
	"fmt"
	"os"
	"path/filepath"

	"conductor/server/internal/protocol"
)

// IsolatedHome wraps a per-spec HOME directory. Created once at spec
// registration time, then reused across invocations. The Codex
// app-server subprocess reads its HOME from this directory on each
// spawn.
//
// Lifecycle:
//
//	spec := home.New("claude-opus-planner", provider="openrouter", ...)
//	if err := spec.Setup(); err != nil { ... }   // writes config.toml + symlinks auth
//	// ... later, possibly many invocations:
//	cmd := exec.CommandContext(ctx, "codex", "app-server")
//	cmd.Env = append(os.Environ(), "HOME="+spec.HomeDir())
//	// (after last invocation, optionally: spec.Remove())
type IsolatedHome struct {
	// specId identifies the spec. The HomeDir is derived from it.
	specId string
	// provider is the Codex model_provider written into config.toml.
	provider string
	// HomeDir is the absolute path to the per-spec HOME.
	homeDir string
	// configToml is the path inside HomeDir for config.toml.
	configToml string
}

// New constructs an IsolatedHome for the given specId + provider.
// It does NOT touch the filesystem; call Setup() for that.
func New(specId, provider string) *IsolatedHome {
	home := SpecHomeDir(specId)
	return &IsolatedHome{
		specId:     specId,
		provider:   provider,
		homeDir:    home,
		configToml: filepath.Join(home, ".codex", "config.toml"),
	}
}

// SpecId returns the spec identifier this HOME belongs to.
func (h *IsolatedHome) SpecId() string { return h.specId }

// HomeDir returns the absolute path to the HOME root.
func (h *IsolatedHome) HomeDir() string { return h.homeDir }

// ConfigTomlPath returns the path inside the HOME where the Codex
// config.toml was written.
func (h *IsolatedHome) ConfigTomlPath() string { return h.configToml }

// Setup prepares the HOME directory: creates it with 0700, writes
// config.toml, symlinks the per-provider auth file into HOME.
//
// baseURL and envKey come from the resolved [model_providers.<id>]
// block in the user's ~/.codex/config.toml. Conductor reads that
// file, picks the right provider, and hands us the values.
//
// The authSourcePath is where the per-provider auth lives in
// $CONDUCTOR_HOME/.auth/<provider>/. If empty, the auth symlink is
// skipped (used by providers that don't need an API key, like
// Ollama or an already-authenticated local proxy).
func (h *IsolatedHome) Setup(baseURL, envKey, authSourcePath string) error {
	if err := os.MkdirAll(filepath.Join(h.homeDir, ".codex"), 0o700); err != nil {
		return fmt.Errorf("mkdir HOME: %w", err)
	}

	// Write config.toml. See docs/design.md §5.2 for the schema.
	toml := fmt.Sprintf(`# Generated by `+"`conductor spec create`"+`. Do not edit by hand
# unless you also understand §6.2.5 of docs/design.md.

model_provider = %q

[model_providers.%s]
name = %q
base_url = %q
`, h.provider, h.provider, h.provider, baseURL)
	if envKey != "" {
		// Empty env_key means "provider doesn't need an API key".
		toml += fmt.Sprintf("env_key = %q\n", envKey)
	}

	if err := os.WriteFile(h.configToml, []byte(toml), 0o600); err != nil {
		return fmt.Errorf("write config.toml: %w", err)
	}

	// Symlink the per-provider auth file. Skip if none configured.
	if authSourcePath == "" {
		return nil
	}
	if _, err := os.Stat(authSourcePath); err != nil {
		// Source doesn't exist yet — that's fine, the symlink would
		// dangle. Skip; the user can populate it via `conductor auth
		// init <provider>` later.
		return nil
	}
	// Codex reads ~/.codex.json (NOT inside .codex/) for auth on
	// some installs. We symlink at the HOME root.
	linkPath := filepath.Join(h.homeDir, ".codex.json")
	if err := os.Symlink(authSourcePath, linkPath); err != nil && !os.IsExist(err) {
		return fmt.Errorf("symlink auth: %w", err)
	}
	return nil
}

// Remove deletes the HOME directory. Spec metadata (spec.json) is
// preserved at the parent — the spec package deletes that separately.
func (h *IsolatedHome) Remove() error {
	if err := os.RemoveAll(h.homeDir); err != nil {
		return fmt.Errorf("remove HOME: %w", err)
	}
	return nil
}

// EnsureAuthDirFile ensures $CONDUCTOR_HOME/.auth/<provider>/auth.json
// exists (creating an empty file if needed). The user populates it
// separately, e.g. via `conductor auth init <provider>`.
//
// authSourcePath is the file we just ensured exists.
func EnsureAuthDirFile(provider string) (string, error) {
	dir := filepath.Join(AuthDir(), provider)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return "", err
	}
	path := filepath.Join(dir, "auth.json")
	if _, err := os.Stat(path); os.IsNotExist(err) {
		if err := os.WriteFile(path, []byte("{}"), 0o600); err != nil {
			return "", err
		}
	}
	return path, nil
}

// Compile-time assertion that *IsolatedHome satisfies a useful
// surface (so reviewers can see at a glance what's intended).
var _ = func() *IsolatedHome {
	return New("example", string(protocol.ProviderCodex))
}()
